service: caffeini
frameworkVersion: '3'


plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  #- serverless-webpack
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2



functions:
  #Jwt.js
  auth:
    handler: src/jwt.auth
  #Auth.js
  createAccount:
    handler: src/auth.createAccount
    events:
      - http:
          path: auth/new
          method: post
  login:
    handler: src/auth.login
    events:
      - http:
          path: auth/local
          method: post
  updateUserInfo:
    handler: src/auth.updateUserInfo
    events:
      - http:
          path: user/info
          method: put
          authorizer: auth
  #Caffeine.js
  addCaffeine:
    handler: src/caffeine.addCaffeineDrink
    events:
      - http:
          path: caffeine
          method: post
          authorizer: auth

#  test:
#    handler: src/auth.test
#    events:
#      - http:
#          path: auth/test
#          method: get
#          authorizer: auth
