service: caffeini
frameworkVersion: '3'


plugins:
  - serverless-dotenv-plugin
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2



functions:
  #Auth.js
  createAccount:
    handler: src/auth.createAccount
    events:
      - http:
          path: auth/new
          method: post
  login:
    handler: src/auth.login
    events:
      - http:
          path: auth/local
          method: get
